insert into t_tj_openaccount(
  `code_oa`,
  `code_bc`,
  `tjpme_token`,
  `member_no`,
  `customer_no`,
  `customer_name`,
  `papers_type`,
  `papers_num`,
  `gender`,
  `province`,
  `city`,
  `area`,
  `trade_pwd`,
  `phone_pwd`,
  `phone`,
  `fax`,
  `post_code`,
  `email`,
  `address`,
  `brokerage_no`,
  `organization_no`,
  `id_type`,
  `bank_acc`,
  `check_bank_card`,
  `create_date`,
  `update_date`,
  `channel`,
  `ytx_user_name`,
  `cancel_flg`
  )

  values select

  1,
  -1,
  `tjpme_token`,
  `member_no`,
  `customer_no`,
  `customer_name`,
  `papers_type`,
  `papers_num`,
  `gender`,
  `province`,
  `city`,
  `area`,
  `trade_pwd`,
  `phone_pwd`,
  `phone`,
  `fax`,
  `post_code`,
  `email`,
  `address`,
  `brokerage_no`,
  `organization_no`,
  `id_type`,
  `bank_acc`,
  `check_bank_card`,
  `create_date`,
  `update_date`,
  `channel`,
  `ytx_user_name`,
  `cancel_flg`

  from t_tj_openaccountlog where customer_no = '160999900000075';

